######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 20 11:01:36 2012
######################################################################

TEMPLATE = app
TARGET = TemporalConstraint
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += ActionStruct.h AddDialog.h ModifDialog.h Solving.h structhead.h
SOURCES += AddDialog.cpp main.cpp ModifDialog.cpp Solving.cpp
